url: http://gundersons.us/josh
name: GunderBlog
description: 'Josh&#039;s Blog'
#theme: jekyll-theme-hacker
baseurl: "/josh"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: [GunderBlog]
description: ['Josh&#039;s Blog']
